name: eth-options-bot-india

services:
  - name: bot
    type: web
    instance_type: free
    
    build:
      type: docker
      dockerfile: Dockerfile
    
    ports:
      - port: 8000
        protocol: http
    
    regions:
      - fra
    
    scaling:
      min: 1
      max: 1
    
    health_checks:
      - http:
          port: 8000
          path: /health
    
    env:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PYTHONUNBUFFERED
        value: "1"
